FROM maven:3.9.12-eclipse-temurin-21 AS builder

WORKDIR /build

COPY pom.xml ./

RUN mvn dependency:go-offline

COPY src src

RUN mvn clean install -DskipTests


FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

COPY --from=builder /build/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT [ "java", "-jar", "/app/app.jar"]